version: '3.1'

services:
  postgres:
    image: postgres:alpine3.20
    healthcheck:
        test: pg_isready -U user
        interval: 1s
        timeout: 60s
        retries: 60
    ports:
        - "5432:5432"
    volumes:
        - postgres_db_vol:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: chat

  chat:
    build: 
      context: .
      dockerfile: Dockerfile.chat
    ports:
        - "8000:8000"
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@postgres:5432/chat
      KAFKA_INSTANCE: kafka:29092

  processor:
    build: 
      context: .
      dockerfile: Dockerfile.processor
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@postgres:5432/chat
      KAFKA_INSTANCE: kafka:29092

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    healthcheck:
        test: nc -z localhost 2181 || exit -1
        interval: 1s
        timeout: 60s
        retries: 60
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    healthcheck:
      test: nc -z localhost 29092 || exit -1
      interval: 1s
      timeout: 60s
      retries: 60
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_db_vol: