FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt

ENV PYTHONPATH=/app

COPY ./app/db ./app/db
COPY ./app/chat ./app/chat

# RUN python ./app/db/db_init.py

CMD ["python", "./app/chat/main.py"]